"""Shared pytest fixtures and import setup for the scaled_up Z80 disassembler suite.

This conftest makes `scripts/z80_disasm.py` importable as `z80_disasm` and exposes
the frozen, human-verified oracle data as fixtures. Every test in this directory
should obtain ground truth from these fixtures rather than recomputing it.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import pytest

# scaled_up/ -> repo root
SCALED_UP = Path(__file__).resolve().parent
REPO_ROOT = SCALED_UP.parent
SCRIPTS = REPO_ROOT / "scripts"
ORACLE = SCALED_UP / "oracle"

# Make the disassembler importable (it ships as a script, not a package).
if str(SCRIPTS) not in sys.path:
    sys.path.insert(0, str(SCRIPTS))
if str(SCALED_UP) not in sys.path:
    sys.path.insert(0, str(SCALED_UP))

# Shared comparison helpers (numeric-aware). Import here so every test can do
# `from conftest import normalize, decode_matches`.
from oracle_compare import decode_matches, normalize  # noqa: E402,F401


def _load_jsonl(path: Path) -> list[dict]:
    with path.open() as f:
        return [json.loads(line) for line in f if line.strip()]


@pytest.fixture(scope="session")
def z80():
    """The module under test."""
    import z80_disasm

    return z80_disasm


@pytest.fixture(scope="session")
def rom() -> bytes:
    """Flat 16 KB Berzerk ROM image, addressable by absolute address.

    Layout matches z80_disasm.ROM_REGIONS: ROM0 @ 0x0000, ROM1 @ 0x1000,
    ROM2 @ 0x1800, ROM3 @ 0x2000, ROM4 @ 0x2800, ROM5 @ 0x3000.
    """
    return (ORACLE / "berzerk_flat.bin").read_bytes()


@pytest.fixture(scope="session")
def decode_oracle() -> list[dict]:
    """Full clean corpus: 5,288 rows of {addr, bytes, expected, len, label}.

    `expected` is the normalized Tunstall reference mnemonic+operands (lowercased,
    single-spaced). Use for differential / coverage tests.
    """
    return _load_jsonl(ORACLE / "decode_oracle.jsonl")


@pytest.fixture(scope="session")
def skoolkit_witness() -> list[dict]:
    """Independent third-party disassembly: 5,288 rows of {addr, skoolkit, len}.

    Produced once by SkoolKit 10's Z80 disassembler (skoolkit.ca) over the same
    ROM and frozen here. NOT generated by this project or by Claude. Use for the
    corroboration category: the decoder must match this outside implementation.
    """
    return _load_jsonl(ORACLE / "skoolkit_instructions.jsonl")


@pytest.fixture(scope="session")
def opcode_shapes() -> list[dict]:
    """One representative row per distinct opcode shape (333 rows).

    Use to guarantee broad opcode-table coverage with a manageable parametrize set.
    """
    return _load_jsonl(ORACLE / "opcode_shapes.jsonl")


@pytest.fixture(scope="session")
def labels() -> dict:
    """{ "0x...": "LABEL" } from the Tunstall reference."""
    return json.loads((ORACLE / "labels.json").read_text())


# `normalize` and `decode_matches` are imported at the top of this file from
# oracle_compare so there is a single source of truth for comparison logic.
